### ISSUE TITLE
possible to run with docker run ?

### ISSUE THREAD

**Issue by v0idp** [itzg/mc-router#11]
Is it possible to run this with docker run and append the command to it. If yes how would i properly map the subdomains to the correct containers ? Because I'm getting "Unable to find registered backend" all the time. Also do I need the SRV Record, if yes can I set the target to a wildcard like *.example.com so one record works for all subdomains ?

**Comment by v0idp** [comment]
Nvm I made it work... made an issue too early.
note to myself: yes you can run it with docker run, but you need to use the ip addresses of the containers.

**Comment by itzg** [comment]
There's some other techniques for addressing the other containers by name rather than IP address such as giving your servers a network alias:

https://docs.docker.com/engine/reference/run/#network-settings

I believe that's what compose is automatically doing for each declared service.

**Comment by v0idp** [comment]
thank you. that's some useful information for the future!
