### ISSUE TITLE
Source IP?

### ISSUE THREAD

**Issue by sfxworks** [itzg/mc-router#13]
I am not sure what the underlying mechanics would be needed to get this working (or if this is even possible with mc-router) though in k8s I have been experimenting with ways to pass the source IP to the user. Known ways are through `externalTrafficPolicy: Local` alongside NodePort or a Load Balancer. Though with mc-router in between this it appears the IP is still hidden from the server. 

Is it possible to pass the source IP to the server while still reading the domain it is using? I hope to use this along-side Cilium's DSR and have been wondering if a similar concept could be applied here.

**Comment by itzg** [comment]
Since mc-router is an inline proxy it is limited by what can be passed via the Minecraft protocol. I don't see a way in the handshaking to pass the proxied/origin IP address

https://wiki.vg/Protocol#Handshake

Let me know if I have missed something though.

**Comment by Gabitzuu** [comment]
Any updates? 

This could be achieved by implementing PROXY protocol and sending the source IP through it. Usually, that's the way to do it, either PROXY protocol or RealIP (tho nowadays PROXY is prefered as that's already implemented in Bungeecord/Spigot)

If you'll implement this, please keep me updated as I'd definetly use this.

**Comment by itzg** [comment]
Thanks for the ping @Gabitzuu . At the time I didn't realize Bungeecord, etc supported `PROXY`. I agree, that seems like a feasible way to add this support.

**Comment by Gabitzuu** [comment]
No worries. If it's possible, can you give an ETA for this implementation?

[here's an example](https://github.com/haveachin/infrared/blob/master/proxy.go#L225-L237) of sending `PROXY`. (Based on https://github.com/pires/go-proxyproto)

**Comment by itzg** [comment]
Thanks for the pointer. I'm thinking about implementing that this weekend...unless I get distracted 😀

**Comment by Gabitzuu** [comment]
Cheers 🍻 . Maybe I'll try to implement it myself and make a PR, even tho I haven't worked with Golang that much... Btw, do you have any Discord server?

**Comment by itzg** [comment]
Sounds good. Oh yeah I should add a link to this Discord server from this repo

https://discord.gg/DXfKpjB
