### ISSUE TITLE
Enable multi-arch build?

### ISSUE THREAD

**Issue by sasanjac** [itzg/mc-router#16]
Hi,

as stated in the title, would it be possible to build this image for multiple platforms? So we can run it on RPis etc.

Thanks!

**Comment by itzg** [comment]
This is a great idea and it looks like goreleaser now supports multi-architecture docker builds.

**Comment by itzg** [comment]
Can you give this multi-arch image a try: `itzg/mc-router:1.11.0-pre2`? I have tested so far on an arm64 VM, but not yet on my RaspberryPi.

**Comment by sasanjac** [comment]
Sadly, I do not have a RPi, only a arm64 RockPI (`linux/arm64/v8`) and `itzg/mc-router:1.11.0-pre1` is working. Thanks!

**Comment by itzg** [comment]
The "latest" and version-tagged images are now multi-arch.
