### ISSUE TITLE
Question: Time of DNS resolution

### ISSUE THREAD

**Issue by jemand771** [itzg/mc-router#18]
Hi,

I'm currently using bungeecord/waterfall to route players between servers (using the "forced hosts" feature), but there's a problem: when using docker's built-in DNS server to resolve container IPs, I can just specify the container hostnames inside my bungeecord config. However, bungeecord doesn't re-resole the DNS entries, so if the minecraft server it self gets a new ip (i.e. the container restarts), bungeecord can't see it anymore

Question: how does mc-router handle this? how/when are hostnames for minecraft servers resolved? only at startup (like in bungeecord) or every once in a while (would be optimal)

**Comment by itzg** [comment]
I would have to research what Go's DNS resolution does, but what you have observed is fairly common with long running services.

**Comment by jemand771** [comment]
thanks for the quick reply! let me know if/when you figure something out.

this is getting off-topic, but if the "industry standard" for minecraft proxies/routers is caching the dns records (and miserably failing once the ip of a server changes), how else are you supposed to use docker for deploying a bungeecord network?

with only one node i could bind all ports to 127.0.0.1 and reference my local ip from bungeecord, but with multiple docker hosts in an overlay network, that's no longer an option. (the only way (that i know of) to figure out on which physical machine a container is currently running is to use docker's built-in container dns)

as a final option, I could constraint all (minecraft) servers to specific (physical) servers and do the local-binding trick mentioned above. that can't be "the right way" to do it, or is it?

**Comment by itzg** [comment]
FYI, I remembered the JVM has an option to configure the DNS resolution cache, so that is now configurable and defaults to 60 seconds for the bungeecord image.

As for mc-router, I confirmed that Go does not cache DNS results so it should be able to handle container IP reassignment without any further configuration.

**Comment by jemand771** [comment]
woah, that's a lot of good news at once - thank you!
