### ISSUE TITLE
Missing doc for kube-discovery (or remove, if unused?)

### ISSUE THREAD

**Issue by vorburger** [itzg/mc-router#23]
What does the kube-discovery config do?

It's mentioned in the README, but not used in the Kubernetes example.

https://github.com/itzg/mc-router/search?q=kube-discovery does not show it actually being used in source code. Is it perhaps something left over that could be removed from the README?

**Comment by vorburger** [comment]
https://github.com/itzg/mc-router/search?q=KubeDiscovery shows the flag exists in code, but that then isn't read anywhere.

Would a PR to rm this from both README and main.go be welcome?

Or am I just missing where it's used?

**Comment by itzg** [comment]
Wow, yeah that indeed seems to be a dead option I was pondering before `--in-kube-cluster`. Yes, a PR would be great.
