### ISSUE TITLE
Prometheus Metrics

### ISSUE THREAD

**Issue by vorburger** [itzg/mc-router#34]
It would be useful if `-metrics-backend prometheus` was supported.

Using https://github.com/go-kit/kit/tree/master/metrics/prometheus this should be doable.

Altnernatively, one could run something like https://github.com/albertito/prometheus-expvar-exporter as a sidecar, but that seems a bit micro service overengineerified (to me).

@itzg would you welcome and merge a PR with this?Perhaps someone reading along here would like to contribute this?

**Comment by itzg** [comment]
I'm already using go-kit, so a solution using that would be preferable.
