### ISSUE TITLE
Docker Swarm Support planend 

### ISSUE THREAD

**Issue by LukasL28** [itzg/mc-router#60]
To explain, I am running a docker swarm cluster, using the mc routuer works as intended, but I have a suggestion. Could you add dynamic support like with kubernetes but with docker labels (like traefik does ist). so you set a label called "mc-router=enabled" and "mc-router=example.domain@example.com"  and now its routs the traffic of the container where the labels are set.

**Comment by itzg** [comment]
Yes this makes sense to have equivalent/similar support for plain Docker and Swarm deployments. I'll get this queued up.

**Comment by Foxite** [comment]
Thanks for supporting docker swarm. If it's not too much trouble can you make this work with non-swarm deployments?

I could do it myself but I can't tell when I'll have time to work on it.

**Comment by itzg** [comment]
@Foxite I'm actually thinking this will work with non-swarm since the same API for getting container labels exists still.

**Comment by Foxite** [comment]
That's what I thought, but right now when I start mc-router in docker swarm mode, it fails to start because "Error response from daemon: This node is not a swarm manager"

**Comment by itzg** [comment]
Thanks for double checking. Can you create a new enhancement issue and link it here?

**Comment by Foxite** [comment]
#110 110
